### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by SirDank** [VolmitSoftware/Iris#1017]
### Problem

1. Build Iris using 2.7.5 release: [https://github.com/VolmitSoftware/Iris/releases/tag/2.7.5-1.20.1](url)
2. Check output file name (Iris-2.7.4-1.20.1.jar)

plugin.yml contents:
```yml
name: Iris
version: 2.7.4-1.20.1
main: com.volmit.iris.Iris
load: STARTUP
authors: [ cyberpwn, NextdoorPsycho, Vatuu ]
website: volmit.com
description: More than a Dimension!
libraries:
  - com.googlecode.concurrentlinkedhashmap:concurrentlinkedhashmap-lru:1.4.2
  - com.github.ben-manes.caffeine:caffeine:3.0.5
  - org.apache.commons:commons-lang3:3.12.0
  - io.timeandspace:smoothie-map:2.0.2
  - com.google.guava:guava:31.0.1-jre
  - com.google.code.gson:gson:2.8.9
  - org.zeroturnaround:zt-zip:1.14
  - it.unimi.dsi:fastutil:8.5.6
  - org.ow2.asm:asm:9.2
  - rhino:js:1.7R2
  - bsf:bsf:2.4.0
commands:
  iris:
    aliases: [ ir, irs ]
api-version: '1.20'
hotload-dependencies: false
```

### Solution

Fix Version Number

### Minecraft Version

1.2

### Iris Version

2.7.5

### Log

N/A
